### ISSUE TITLE
ubuntu 16.04 : master fails to compile, v0.9.4 works

### ISSUE THREAD

**Issue by schnerchi** [monero-project/bitmonero#905]
maybe someone with more knowledge can have a look : 

http://pastebin.com/DKYCgsDt

**Comment by schnerchi** [comment]
more info : http://pastebin.com/Wh0eP1Hm

**Comment by moneromooo-monero** [comment]
This doesn't seem to include the error.
In the future, can you also please put logs either in the bug itself if not too loing, or on fpaste.org ? I usually can't get to pastebin.com as they'll block tor exit nodes 95% of the time, though I got lucky today :)

**Comment by iDunk5400** [comment]
@schnerchi Maybe you should try cloning master into a folder that does not contain a space in its name.

**Comment by moneroexamples** [comment]
Did you check instructions here:

- https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04

**Comment by radfish** [comment]
(Just a minor sidenote: please do not use fpaste.org either because they expire. There are issues here without any information except the dead link to fpaste.org. Github has perfectly usable file attachment feature: via drag-drop or the link right below. Use that please; in addition to pasting the most relevant chunk inline. Thanks.)

**Comment by schnerchi** [comment]
Ok, issue solved. Problem was/is the space in the folder name. So something must have changed between 0.9.4 and MASTER that causes this.

Thanks everybody!
