### ISSUE TITLE
Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/bitmonero#983]
Looks like this is another dependency on Ubuntu 16.04:

libgtest-dev

And actually this is more complicated than it first seems because:
1. It doesn't come compiled
2. It doesn't actually work even if compiled

So I've tried compiling googletest from their git repo with no success yet...still getting failures on 'make test' for googletest itself (version 1.7.0)

Could I request future versions also include the test suite?

**Comment by radfish** [comment]
First a note: gtest is included in the source tree as a vendored dependency, so bitmonerod will build fine without gtest installed on the system. But agreed that it should also build with gtest installed on system, if one is found. I think there are two problems with that currently
1. #980 -- a bug in cmake script
2. no package on Ubuntu with built gtest (judging from your report; on Arch gest pkg does include libgtest.so) -- do you know why? there must be some reason.

Sidenote: since cmake does build the tests with in-tree gtest successfully, you could compare that working build of gest with your standalone build of gtest.

**Comment by NanoAkron** [comment]
Thanks @radfish. Can you give me any tips how to run the tests with in-tree gtest? 

make release-test just borks.

**Comment by radfish** [comment]
Can you uninstall the gtest package (libgtest-dev I guess) from your system and try again?
Also, where does it bork, could you paste the output please?

**Comment by radfish** [comment]
gtest patch merged, this can be closed

**Comment by NanoAkron** [comment]
Thanks! Will test this weekend hopefully.
